LOAD DATA INFILE '$$$/customer.csv' INTO TABLE customer FIELDS TERMINATED BY '|';
LOAD DATA INFILE '$$$/lineitem.csv' INTO TABLE lineitem FIELDS TERMINATED BY '|';
LOAD DATA INFILE '$$$/nation.csv' INTO TABLE nation FIELDS TERMINATED BY '|';
LOAD DATA INFILE '$$$/orders.csv' INTO TABLE orders FIELDS TERMINATED BY '|';
LOAD DATA INFILE '$$$/part.csv' INTO TABLE part FIELDS TERMINATED BY '|';
LOAD DATA INFILE '$$$/partsupp.csv' INTO TABLE partsupp FIELDS TERMINATED BY '|';
LOAD DATA INFILE '$$$/region.csv' INTO TABLE region FIELDS TERMINATED BY '|';
LOAD DATA INFILE '$$$/supplier.csv' INTO TABLE supplier FIELDS TERMINATED BY '|';
